# This is a basic workflow to help you get started with Actions

name: secret_test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Remote SSH commands using key
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: echo Success

