# This is a basic workflow to help you get started with Actions

name: secret_test

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Echo a test secret
        run: echo ${{secrets.MY_SECRET}}

